title: julian jarjour
description: >- 
  julian's essays and things
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
defaults:
  - scope:
      path: ""
      type: "writing"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "poetry"
    values:
      layout: "poem"
collections:
  writing:
    output: true
  projects:
    output: true
  poetry:
    output: true
