title: julian jarjour
email: abc@mail.com
description: >- 
  julian's essays and things
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
defaults:
  - scope:
      path: ""
      type: "essays"
    values:
      layout: "essay"
  - scope:
      path: ""
      type: "poetry"
    values:
      layout: "poem"
collections:
  essays:
    output: true
  poetry:
    output: true
